baseurl: ""
url: "https://repod.xyz"
title: Random Encounters Podcast
description: Connect with us on YouTube, Instagram, and Twitter
plugins:
  - jekyll-seo-tag
  - jekyll-feed
collections:
  episodes:
    output: true
    permalink: /:name
